version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app-demo
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-server-demo
    ports:
      - "8081:81"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql-demo
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel
    ports:
      - "3310:3306" # Change if 3306 is used locally

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-queue-worker
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - app
      - mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql-data: {}